repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.260'
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.16
    hooks:
      - id: djlint-django
  
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.1'
    hooks:
      - id: poetry-export
        args: [
          "-f", "requirements.txt",
          "-o", "requirements.txt",
          "--without-hashes"
        ]

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint
      language: system
      types: [python]
      args:
        [
          "-rn",
          "-sn",
        ]
      exclude: ^manage\.py$
